services:
  kfk1:
    image: confluentinc/cp-kafka:7.7.1
    restart: on-failure
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ../data/kfk1/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kfk1:19092,DOCKER://host.docker.internal:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka-overlay

networks:
  kafka-overlay:
    external: true